[project]
name = "qrng"
version = "0.1.0"
description = "Quantum Random Number Generator"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.7",
    "pylatexenc>=2.10",
    "qiskit>=2.2.1",
    "qiskit-aer>=0.17.2",
]
