name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/ruff-action@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install mypy qiskit qiskit-aer matplotlib
      - run: mypy . --ignore-missing-imports